# Generated by Django 5.1.3 on 2024-12-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('critic', 'Critic'), ('user', 'User')], default='user', max_length=255),
        ),
    ]
