# Generated by Django 5.1.2 on 2024-11-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_app_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
