# Generated by Django 5.0.4 on 2024-12-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='helpful_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
