# Generated by Django 5.1.3 on 2024-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(blank=True, through='core.GameCategory', to='core.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(blank=True, through='core.GamePlatform', to='core.platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, through='core.GameTag', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
