# Generated by Django 5.1.2 on 2024-12-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_description_customuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='parent_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlcs', to='core.game'),
        ),
    ]
