# Generated by Django 5.1.3 on 2024-12-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_review_helpful_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
